load("@//bazel:api.bzl", "mojo_library")

mojo_library(
    name = "xmojo",
    srcs = glob(["*.mojo"]),
    validate_missing_docs = False,
    deps = [
        "//:max",
        "//:std",
    ],
)

mojo_library(
    name = "xmojo_base",
    srcs = [
        "__init__.mojo",
        "spirv.mojo",
    ],
    validate_missing_docs = False,
    deps = ["//:std"],
)
